# Calculating medians, percentiles and interquartile ranges

This notebook loads `results/samples_comparative_gwp_contributions.csv` and calculates medians, percentiles and interquartile ranges for total scores and specific contributions. 

The resulting tables are saved to `results/stats_totals.csv`, `results/stats_totals.csv` and `results/stats_metals.csv`.

In [13]:
import brightway2 as bw
import bw2calc as bc
import bw2data as bd
import numpy as np
import pandas as pd
import presamples as ps
import arviz as az

In [14]:
samples_combined = pd.read_csv("results/samples_comparative_gwp_contributions_endoflife_included.csv")

## Total GWPs statistical analysis

In [15]:
samples_combined_excl_total =  samples_combined[samples_combined['component'] != 'Total']
total = samples_combined_excl_total.groupby(['scenario', 'energy_scenario','iteration'])['score'].sum().reset_index()

In [16]:
grouped = total.groupby(['scenario', 'energy_scenario'])

def calculate_percentiles_and_iqr(group):
    mean = group['score'].mean()
    median = group['score'].median()
    minimum = group['score'].min()
    maximum = group['score'].max()
    q25 = group['score'].quantile(0.25)
    q75 = group['score'].quantile(0.75)
    iqr = q75 - q25
    #hdi_90 = az.hdi(group['score'].to_numpy(), hdi_prob=.9)
    #hdi_90_lower = hdi_90[0]
    #hdi_90_upper = hdi_90[1]
    return pd.Series({'mean': mean, 'median': median, 'minimum': minimum, 'maximum': maximum, '25th Percentile': q25, '75th Percentile': q75, 'IQR': iqr})

stats_totals = grouped.apply(calculate_percentiles_and_iqr).reset_index()
stats_totals

C:\Users\rla44\AppData\Local\Temp\ipykernel_28732\3015953135.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stats_totals = grouped.apply(calculate_percentiles_and_iqr).reset_index()

,scenario,energy_scenario,mean,median,minimum,maximum,25th Percentile,75th Percentile,IQR
0,AM HTO,Current,13.397266,13.369392,11.853200,19.108515,13.011330,13.740544,0.729213
1,AM HTO,Greener,10.507699,10.477924,9.166972,14.022923,10.182862,10.774983,0.592121
2,AM HTO (steel jig),Current,11.945393,11.944516,10.576953,14.758038,11.659430,12.236522,0.577092
3,AM HTO (steel jig),Greener,8.355036,8.330582,7.405100,10.189364,8.123936,8.568173,0.444237
4,CM HTO,Current,10.725431,10.675280,8.409235,14.945944,10.004531,11.420960,1.416428
5,UKR,Current,37.959267,37.933581,32.580259,43.570434,36.876031,38.954482,2.078451

In [17]:
stats_totals.to_csv("results/stats_totals.csv", index=False)

## Material and manufacture GWP statistical analysis

Here only the impact of instruments (material and manufacture) and implant (material and manufacture) are considered.

In [18]:
components_to_exclude = ['Anesthesia', 'Packaging', 'Transport', 'Sterilisation', 'Argon']
total_contributions_filtered = samples_combined_excl_total[~samples_combined_excl_total['component'].isin(components_to_exclude)]
total_contributions_summed = total_contributions_filtered.groupby(['scenario', 'energy_scenario', 'iteration'])['score'].sum().reset_index()

In [19]:
grouped = total_contributions_summed.groupby(['scenario', 'energy_scenario'])
stats_material_manufacture = grouped.apply(calculate_percentiles_and_iqr).reset_index()
stats_material_manufacture['component'] = 'instruments and implant (mat and mnf)'
stats_material_manufacture

C:\Users\rla44\AppData\Local\Temp\ipykernel_28732\1850199959.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stats_material_manufacture = grouped.apply(calculate_percentiles_and_iqr).reset_index()

,scenario,energy_scenario,mean,median,minimum,maximum,25th Percentile,75th Percentile,IQR,component
0,AM HTO,Current,9.439946,9.410945,8.136805,15.018375,9.082348,9.757079,0.674731,instruments and implant (mat and mnf)
1,AM HTO,Greener,6.541040,6.505622,5.327630,9.919082,6.281692,6.758345,0.476653,instruments and implant (mat and mnf)
2,AM HTO (steel jig),Current,7.993835,7.979466,6.917458,10.673478,7.746512,8.227999,0.481488,instruments and implant (mat and mnf)
3,AM HTO (steel jig),Greener,4.394113,4.381339,3.626601,6.092269,4.213602,4.546892,0.333290,instruments and implant (mat and mnf)
4,CM HTO,Current,5.612045,5.553278,3.454301,10.030072,4.908864,6.273653,1.364789,instruments and implant (mat and mnf)
5,UKR,Current,29.365986,29.305033,24.263850,34.736384,28.322802,30.289580,1.966778,instruments and implant (mat and mnf)

In [20]:
stats_material_manufacture.to_csv("results/stats_material_manufacture.csv", index=False)

## Metal impacts (workpiece, powder and ingot) GWP statistical analysis

In [21]:
metal_impacts = pd.read_csv("results/metal_gwp.csv")

In [22]:
def calculate_percentiles_and_iqr(group):
    mean = group['score'].mean()
    median = group['score'].median()
    q25 = group['score'].quantile(0.25)
    q75 = group['score'].quantile(0.75)
    iqr = q75 - q25
    #hdi_90 = az.hdi(group['score'].to_numpy(), hdi_prob=.9)
    #hdi_90_lower = hdi_90[0]
    #hdi_90_upper = hdi_90[1]
    return pd.Series({'mean': mean, 'median': median, '25th Percentile': q25, '75th Percentile': q75, 'IQR': iqr})

stats_metals = metal_impacts.groupby('material').apply(calculate_percentiles_and_iqr).reset_index()

stats_metals

C:\Users\rla44\AppData\Local\Temp\ipykernel_28732\3851785293.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stats_metals = metal_impacts.groupby('material').apply(calculate_percentiles_and_iqr).reset_index()

,material,mean,median,25th Percentile,75th Percentile,IQR
0,CoCr,32.630329,32.477687,31.416099,33.730888,2.314789
1,Ti6Al4V_powder,59.840800,59.393430,56.924139,62.003673,5.079533
2,Ti6Al4V_workpiece,52.023082,51.768341,49.798086,53.939948,4.141861
3,UHMWPE,3.182378,3.145252,2.617577,3.686740,1.069163
4,stainless_steel,6.707712,6.499470,5.924961,7.318991,1.394030

In [23]:
stats_metals.to_csv("results/stats_metals.csv", index=False)

In [24]:
#def calculate_percentiles(series, mean_score, lower_percentile, upper_percentile):
#    adjusted_series = series - mean_score
#    lower_value = np.percentile(adjusted_series, lower_percentile)
#    upper_value = np.percentile(adjusted_series, upper_percentile)
#    return lower_value, upper_value

#percentiles = (
#    total
#    .groupby(['scenario', 'energy_scenario'])
#    .apply(lambda x: calculate_percentiles(x['score'], 
#                                           mean_scores.loc[(mean_scores['scenario'] == x.name[0]) & 
#                                                           (mean_scores['energy_scenario'] == x.name[1]), 'mean_score'].values[0],
#                                           2.5, 97.5))
#    .reset_index()
#)
#percentiles[['2.5th_percentile', '97.5th_percentile']] = pd.DataFrame(percentiles[0].tolist(), index=percentiles.index)
#percentiles.drop(columns=[0], inplace=True)
#percentiles